---

- name: remove ubuntu-web-launchers package (to remove amazon spam)
  package:
    name: ubuntu-web-launchers
    state: absent

- name: remove remaining .desktop file if required
  file:
   path: /etc/skel/.local/share/applications/ubuntu-amazon-default.desktop
   state: absent

