---

- name: Remove ubuntu-web-launchers package (to remove amazon spam)
  ansible.builtin.package:
    name: ubuntu-web-launchers
    state: absent

- name: Remove remaining .desktop file if required
  ansible.builtin.file:
    path: /etc/skel/.local/share/applications/ubuntu-amazon-default.desktop
    state: absent
